# Generated by Django 3.1.13 on 2023-04-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='leave_date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='leave_date_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
