# Generated by Django 3.1.13 on 2023-04-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0002_auto_20230413_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_denied',
            field=models.BooleanField(default=False),
        ),
    ]
