# Generated by Django 3.1.13 on 2023-04-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0003_request_is_denied'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='sys_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
